version: "2"

run:
  timeout: 10m
  allow-parallel-runners: true
  relative-path-mode: gomod
  tests: true

issues:
  uniq-by-line: true

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: "api/*"
        linters:
          - lll
      - path: "internal/*"
        linters:
          - dupl
          - lll
  settings:
    nolintlint:
      require-specific: true
    revive:
      rules:
        - name: comment-spacings

formatters:
  enable:
    - gofmt
    - goimports

output:
  formats:
    text:
      colors: false
      print-linter-name: true
      print-issued-lines: true
  show-stats: false
