# permissions for end users to view libraries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operatarr
    app.kubernetes.io/managed-by: kustomize
  name: library-viewer-role
rules:
- apiGroups:
  - feddema.dev
  resources:
  - libraries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - feddema.dev
  resources:
  - libraries/status
  verbs:
  - get
