---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - feddema.dev
  resources:
  - medialibraries
  - sonarrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - feddema.dev
  resources:
  - medialibraries/finalizers
  - sonarrs/finalizers
  verbs:
  - update
- apiGroups:
  - feddema.dev
  resources:
  - medialibraries/status
  - sonarrs/status
  verbs:
  - get
  - patch
  - update
