# permissions for end users to view sonarrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operatarr
    app.kubernetes.io/managed-by: kustomize
  name: sonarr-viewer-role
rules:
- apiGroups:
  - feddema.dev
  resources:
  - sonarrs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - feddema.dev
  resources:
  - sonarrs/status
  verbs:
  - get
